In [1]:
import numpy as np

In [2]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
matrix_1s = np.ones(5)
print(matrix_1s)

[1. 1. 1. 1. 1.]


In [6]:
matrix_1s.dtype

dtype('float64')

In [7]:
matrix_1s = np.ones((3,4))
print(matrix_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
matrix_1s = np.ones((3,4), dtype =int)
print(matrix_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
matrix_0s = np.zeros((4,6))
print(matrix_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
matrix_0s = np.zeros((4,6), dtype = bool)
print(matrix_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [12]:
matrix_0s = np.zeros((4,6), dtype = str)
print(matrix_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [13]:
empty_str = ''
print(bool(empty_str))

False


In [16]:
empty_mat = np.empty((3,3))
print(empty_mat)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 6.937e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


# Numpy Functions:

In [17]:
import numpy as np

# arange()

In [18]:
#np.arange(start,end,steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


# linspace()

In [20]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()


In [21]:
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [25]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [26]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [27]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [28]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])