# Random Sampling with Numpy

In [1]:
import numpy as np
import random 

In [2]:
np.random.random(1) #1D array

array([0.78270343])

In [4]:
np.random.random((3,3)) #2D array

array([[0.99015707, 0.81522614, 0.38854908],
       [0.3622906 , 0.09377936, 0.901055  ],
       [0.83790609, 0.69703941, 0.16310657]])

In [6]:
np.random.randint(1,4)  #int type ar single value ar jnno 

3

In [7]:
np.random.randint(1,4, (4,4))  #2D array create fixed range 

array([[2, 3, 1, 2],
       [3, 3, 3, 1],
       [3, 3, 2, 1],
       [2, 2, 3, 3]])

In [8]:
np.random.randint(1,4, (2,4,4)) 

array([[[1, 2, 1, 1],
        [2, 2, 3, 1],
        [3, 3, 2, 1],
        [2, 2, 1, 1]],

       [[3, 1, 3, 1],
        [1, 3, 1, 2],
        [2, 1, 3, 1],
        [1, 1, 1, 2]]])

In [13]:
np.random.seed (10) #same random number generate 
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [14]:
2**32-1

4294967295

In [15]:
np.random.seed (10)
np.random.randint(1,4, (2,4,4))


array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [16]:
np.random.rand(3) #1D array create

array([0.13145815, 0.41366737, 0.77872881])

In [17]:
np.random.rand(3,3) #2D array create

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [18]:
np.random.randn(3,3) #negative positive value.sample return standard normal distribution

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [19]:
x = [1,2,3,4]
np.random.choice(x)

1

In [20]:
np.random.choice(x)

1

In [21]:
for i in range(20):
    print(np.random.choice(x))

1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3


In [22]:
x

[1, 2, 3, 4]

In [23]:
np.random.permutation(x)

array([2, 4, 1, 3])

In [24]:
np.random.permutation(x)

array([2, 3, 4, 1])

# String operations, Comparison and information

In [25]:
ch_name = "Indian AI Production"
str1 = "Learning Python Numpy"

In [26]:
np.char.add(ch_name,str1)

array('Indian AI ProductionLearning Python Numpy', dtype='<U41')

In [27]:
np.char.lower(ch_name)

array('indian ai production', dtype='<U20')

In [28]:
np.char.upper(str1)

array('LEARNING PYTHON NUMPY', dtype='<U21')

In [30]:
np.char.center(str1,60)

array('                   Learning Python Numpy                    ',
      dtype='<U60')

In [31]:
np.char.center(str1,60, fillchar="*")

array('*******************Learning Python Numpy********************',
      dtype='<U60')

In [32]:
np.char.split(ch_name)

array(list(['Indian', 'AI', 'Production']), dtype=object)

In [33]:
np.char.splitlines("hello\nIndian")

array(list(['hello', 'Indian']), dtype=object)

In [34]:
str4 = "dmy"
str5 = "dmy"

In [35]:
np.char.join([":","/"],[str4,str5])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [36]:
np.char.replace(ch_name, "AI","Artificial Intelligence")

array('Indian Artificial Intelligence Production', dtype='<U41')

In [37]:
np.char.equal(str4,str5)

array(True)

In [38]:
np.char.count(ch_name,"a")

array(1)

In [40]:
ch_name

'Indian AI Production'

In [41]:
np.char.find(ch_name,"AI")

array(7)